FROM nginx

RUN apt-get update

RUN apt-get -y --no-install-recommends install \
    bash \
    openssl

RUN apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

# Directories
ADD code/public /var/www/html/public
ADD config/nginx/conf.d /etc/nginx/conf.d

# Files
ADD config/nginx/nginx.conf /etc/nginx/nginx.conf

WORKDIR /var/www/html/public

CMD ["nginx", "-c", "/etc/nginx/nginx.conf", "-g", "daemon off;"]
