#!/usr/bin/env bash

projectName="PrimerTestProject"

firstArg="$1"
lastArgs="$2 $3 $4 $5 $6 $7 $8 $9"

if [[ $firstArg == 'phpunit' ]]; then
	docker exec -it php-${projectName} ../vendor/bin/phpunit ${lastArgs}
fi

if [[ $firstArg == 'phinx' ]]; then
	docker exec -it php-${projectName} ../vendor/bin/phinx ${lastArgs}
fi

if [[ $firstArg == 'composer' ]]; then
	docker exec -it php-${projectName} composer ${lastArgs}
fi

if [[ $firstArg == 'nginx' ]]; then
	docker exec -it nginx-${projectName} nginx ${lastArgs}
fi
